### ISSUE TITLE
command line for  0_coverage.pl

### ISSUE THREAD

**Issue by Chris-lang478** [ntm/grexome-TIMC-Secondary#7]
@ntm 
I am trying to follow your instruction in  0_coverage.pl to make coverage files.
I am so new to perl language. And perl  0_coverage.pl --help is empty. I don't know how to add the samples xlsx, candidatesFiles $transciptsFile , $gvcf (must be  tabix-indexed), and an $outDir.

 In your script, it wrote that 
@ARGV == 5) ||
    die "E $0: needs 5 args: a samples file, a comma-separated list of candidatesFiles, a tsv.gz, a GVCF and an outDir\n";
my ($samplesFile, $candidatesFiles, $transcriptsFile, $gvcf, $outDir) = @ARGV.

What should I do?And there is something like  lib "/home/nthierry/Software/VariantEffectPredictor/ensembl-vep/"， Should I modify it?
 Thanks again!!

Best regards,
Chris

**Comment by ntm** [comment]
I'm not sure if the coverage info is really useful, that's why I didn't package or document it cleanly (eg --help).
Basically it uses the classical/simple way of getting its arguments rather than the more powerful arg parsing with GetOpt, ie instead of e.g. `--arg1 val1 --arg2 val2` , you just call the script with the arguments in the order expected by the script.
Example:
`perl 0_coverage.pl  sampleCLN.xlsx yourCandidateGenes.xlsx canonicalTranscripts_220717.tsv.gz grexome0001.g.vcf.gz CoverageDir/ `
You would have to prepend the appropriate path for each file.
You would also need to run this command once for each GVCF.
And since this script uses the Bio::DB::HTS::Tabix module, you need to have a working copy of this module, accessible to the script. In my case this module is built when installing/updating VEP, and is available in the VEP install subdir. On my systems this is: `/home/nthierry/Software/VariantEffectPredictor/ensembl-vep/`. However since this subdir is not in my default PERL search path, I hardcoded it with `use lib "path/to/ensembl-vep/";`. You may need to do the same.
But really, this coverage info is not super useful in my opinion.

**Comment by Chris-lang478** [comment]
Thanks for your suggestion. I just gave it up.
